/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: sanity/schema.json
export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
};

export type TwitterEmbed = {
  _type: "twitterEmbed";
  url?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  language?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "article";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "comment";
      };
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  language?: string;
  email?: string;
  message?: string;
  article?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "article";
  };
  approved?: boolean;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & TwitterEmbed)
  >;
  audio?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  publishedAt?: string;
  comments?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "comment";
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoEmbed
  | TwitterEmbed
  | Category
  | Slug
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | Comment
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/queries/articles.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug && language == $locale][0] {    _id,    title,    publishedAt,    "slug": slug.current,    "translations": *[      _type == ^._type &&       _id match string::split(^._id, "__i18n_")[0] + "*" &&       _id != ^._id &&       !(_id in path('drafts.**'))    ] {      "language": language,      "slug": slug.current    },    "author": author-> {      name,      "slug": slug.current    },    "audioUrl": audio.asset->url,    "mainImage": {      "url": mainImage.asset->url,      "caption": mainImage.caption,    },    "categories": categories[]-> {      name,       "slug": slug.current,    },    "content": content[]{      ...,      // Portable Text images      _type == "image" => {        alt,        "url": asset->url      },      // Uploaded video (file) + optional external URL      _type == "videoUpload" => {        "videoFileUrl": videoFile.asset->url      },      // Social post embed      _type == "socialMediaPost" => {        url      }    }  }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  translations: Array<{
    language: string | null;
    slug: string | null;
  }>;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  audioUrl: string | null;
  mainImage: {
    url: string | null;
    caption: string | null;
  };
  categories: Array<{
    name: string | null;
    slug: string | null;
  }> | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        _type: "image";
        _key: string;
        url: string | null;
      }
    | {
        _key: string;
        _type: "twitterEmbed";
        url?: string;
      }
    | {
        _key: string;
        _type: "videoEmbed";
        url?: string;
      }
  > | null;
} | null;

// Source: sanity/queries/articles.ts
// Variable: ALL_ARTICLES_QUERY
// Query: *[_type == "article" && language == $locale && !(_id in path('drafts.**'))] | order(publishedAt desc) [$start...$end] {    _id,    title,    publishedAt,    "slug": slug.current,    "author": author->{      name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,     "excerpt": pt::text(content[_type == "block"][0...1]),    "category": categories[0]-> {      name,      "slug": slug.current    }  }
export type ALL_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  excerpt: string;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/articles.ts
// Variable: TOTAL_ARTICLES_COUNT
// Query: count(*[_type == "article" && language == $locale && !(_id in path('drafts.**'))])
export type TOTAL_ARTICLES_COUNT_RESULT = number;

// Source: sanity/queries/articles.ts
// Variable: ARTICLES_BY_CATEGORY_QUERY
// Query: *[_type == "article" && $slug in categories[]->slug.current && language == $locale && !(_id in path('drafts.**'))] | order(publishedAt desc) [$start...$end] {    _id,    title,    publishedAt,    "slug": slug.current,    "author": author-> {       name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,    "category": categories[0]->{       name,      "slug": slug.current,    },     "excerpt": pt::text(content[_type == "block"][0...1])  }
export type ARTICLES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
  excerpt: string;
}>;

// Source: sanity/queries/articles.ts
// Variable: ARTICLES_BY_AUTHOR_QUERY
// Query: *[_type == "article" && author._ref == $authorId && language == $locale && !(_id in path('drafts.**'))] | order(publishedAt desc) [$start...$end] {     _id,    title,    publishedAt,    "slug": slug.current,    "author": author-> {       name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,      "category": categories[0]->{       name,      "slug": slug.current,    },     "excerpt": pt::text(content[_type == "block"][0...1])  }
export type ARTICLES_BY_AUTHOR_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
  excerpt: string;
}>;

// Source: sanity/queries/articles.ts
// Variable: RELATED_ARTICLES_QUERY
// Query: *[    _type == "article" &&     _id != $articleId &&     language == $locale &&     !(_id in path('drafts.**')) &&    // Safely checks if the current article's category slugs exist in the passed array    count(categories[@->slug.current in $categorySlugs]) > 0  ] | order(publishedAt desc) [0...3] {    _id,    title,    publishedAt,    "slug": slug.current,    "author": author->{      name,      "slug": slug.current,    },    "mainImage": mainImage.asset->url,     "excerpt": pt::text(content[_type == "block"][0...1]),    "category": categories[0]-> {      name,      "slug": slug.current    }  }
export type RELATED_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  excerpt: string;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/articles.ts
// Variable: SEARCH_ARTICLES_QUERY
// Query: *[  _type == "article" &&   language == $locale &&   (title match $searchTerm + "*" || pt::text(content) match $searchTerm + "*")] | order(publishedAt desc) [0...12] {   _id,  title,  publishedAt,  "slug": slug.current,  "author": author->{    name,    "slug": slug.current  },  "mainImage": mainImage.asset->url,   "excerpt": pt::text(content[_type == "block"][0...1]),  "category": categories[0]-> {    name,    "slug": slug.current  }}
export type SEARCH_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  publishedAt: string | null;
  slug: string | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  mainImage: string | null;
  excerpt: string;
  category: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/queries/authors.ts
// Variable: GET_AUTHOR_BY_SLUG
// Query: *[_type == "author" && slug.current == $slug && language == $locale && !(_id in path('drafts.**'))][0]{    _id,    name,     bio,    "image": image.asset->url,    "alt": image.alt,    socials[]{platform, url},    // Fetch translations for the Language Switcher    "translations": *[      _type == ^._type &&       _id match string::split(^._id, "__i18n_")[0] + "*" &&       _id != ^._id &&       !(_id in path('drafts.**'))    ] {      "language": language,      "slug": slug.current    }  }
export type GET_AUTHOR_BY_SLUG_RESULT = {
  _id: string;
  name: string | null;
  bio: string | null;
  image: string | null;
  alt: null;
  socials: null;
  translations: Array<{
    language: null;
    slug: string | null;
  }>;
} | null;

// Source: sanity/queries/authors.ts
// Variable: ARTICLES_IN_AUTHOR_COUNT
// Query: count(*[    _type == "article" &&    author._ref == $authorId &&    language == $locale &&     !(_id in path('drafts.**'))  ])
export type ARTICLES_IN_AUTHOR_COUNT_RESULT = number;

// Source: sanity/queries/authors.ts
// Variable: AUTHOR_BY_ARTICLE_ID
// Query: *[_type == "article" && _id == $articleId && !(_id in path('drafts.**'))][0].author-> {    name,    "slug": slug.current,    bio  }
export type AUTHOR_BY_ARTICLE_ID_RESULT = {
  name: string | null;
  slug: string | null;
  bio: string | null;
} | null;

// Source: sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category" && language == $locale && !(_id in path('drafts.**'))] | order(name asc) {    _id,    name,    "slug": slug.current  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
}>;

// Source: sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug && language == $locale && !(_id in path('drafts.**'))][0] {    _id,    name,    "slug": slug.current,    description,        // Fetch translations for the Language Switcher    "translations": *[      _type == ^._type &&       _id match string::split(^._id, "__i18n_")[0] + "*" &&       _id != ^._id &&       !(_id in path('drafts.**'))    ] {      "language": language,      "slug": slug.current    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  translations: Array<{
    language: string | null;
    slug: string | null;
  }>;
} | null;

// Source: sanity/queries/categories.ts
// Variable: ARTICLES_IN_CATEGORY_COUNT
// Query: count(*[    _type == "article" &&     $slug in categories[]->slug.current &&     language == $locale &&     !(_id in path('drafts.**'))  ])
export type ARTICLES_IN_CATEGORY_COUNT_RESULT = number;

// Source: sanity/queries/comments.ts
// Variable: GET_COMMENTS_BY_ARTICLE
// Query: *[_type == "comment" && approved == true && article._ref == $_id && !(_id in path('drafts.**'))] | order(_createdAt desc) [$start...$end] {     _id,     name,    message,    _createdAt  }
export type GET_COMMENTS_BY_ARTICLE_RESULT = Array<{
  _id: string;
  name: string | null;
  message: string | null;
  _createdAt: string;
}>;

// Source: sanity/queries/comments.ts
// Variable: TOTAL_COMMENTS_COUNT
// Query: count(*[    _type == "comment" &&    approved == true &&    article._ref == $_id && // Fixed typo here (was article_ref)    !(_id in path('drafts.**'))  ])
export type TOTAL_COMMENTS_COUNT_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "article" && slug.current == $slug && language == $locale][0] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "translations": *[\n      _type == ^._type && \n      _id match string::split(^._id, "__i18n_")[0] + "*" && \n      _id != ^._id && \n      !(_id in path(\'drafts.**\'))\n    ] {\n      "language": language,\n      "slug": slug.current\n    },\n\n    "author": author-> {\n      name,\n      "slug": slug.current\n    },\n    "audioUrl": audio.asset->url,\n    "mainImage": {\n      "url": mainImage.asset->url,\n      "caption": mainImage.caption,\n    },\n    "categories": categories[]-> {\n      name, \n      "slug": slug.current,\n    },\n    "content": content[]{\n      ...,\n      // Portable Text images\n      _type == "image" => {\n        alt,\n        "url": asset->url\n      },\n      // Uploaded video (file) + optional external URL\n      _type == "videoUpload" => {\n        "videoFileUrl": videoFile.asset->url\n      },\n      // Social post embed\n      _type == "socialMediaPost" => {\n        url\n      }\n    }\n  }\n': ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "article" && language == $locale && !(_id in path(\'drafts.**\'))] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author": author->{\n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url, \n    "excerpt": pt::text(content[_type == "block"][0...1]),\n    "category": categories[0]-> {\n      name,\n      "slug": slug.current\n    }\n  }\n': ALL_ARTICLES_QUERY_RESULT;
    "count(*[_type == \"article\" && language == $locale && !(_id in path('drafts.**'))])": TOTAL_ARTICLES_COUNT_RESULT;
    '\n  *[_type == "article" && $slug in categories[]->slug.current && language == $locale && !(_id in path(\'drafts.**\'))] | order(publishedAt desc) [$start...$end] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author": author-> { \n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url,\n    "category": categories[0]->{ \n      name,\n      "slug": slug.current,\n    }, \n    "excerpt": pt::text(content[_type == "block"][0...1])\n  }\n': ARTICLES_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "article" && author._ref == $authorId && language == $locale && !(_id in path(\'drafts.**\'))] | order(publishedAt desc) [$start...$end] { \n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author": author-> { \n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url,  \n    "category": categories[0]->{ \n      name,\n      "slug": slug.current,\n    }, \n    "excerpt": pt::text(content[_type == "block"][0...1])\n  }\n': ARTICLES_BY_AUTHOR_QUERY_RESULT;
    '\n  *[\n    _type == "article" && \n    _id != $articleId && \n    language == $locale && \n    !(_id in path(\'drafts.**\')) &&\n    // Safely checks if the current article\'s category slugs exist in the passed array\n    count(categories[@->slug.current in $categorySlugs]) > 0\n  ] | order(publishedAt desc) [0...3] {\n    _id,\n    title,\n    publishedAt,\n    "slug": slug.current,\n    "author": author->{\n      name,\n      "slug": slug.current,\n    },\n    "mainImage": mainImage.asset->url, \n    "excerpt": pt::text(content[_type == "block"][0...1]),\n    "category": categories[0]-> {\n      name,\n      "slug": slug.current\n    }\n  }\n': RELATED_ARTICLES_QUERY_RESULT;
    '*[\n  _type == "article" && \n  language == $locale && \n  (title match $searchTerm + "*" || pt::text(content) match $searchTerm + "*")\n] | order(publishedAt desc) [0...12] { \n  _id,\n  title,\n  publishedAt,\n  "slug": slug.current,\n  "author": author->{\n    name,\n    "slug": slug.current\n  },\n  "mainImage": mainImage.asset->url, \n  "excerpt": pt::text(content[_type == "block"][0...1]),\n  "category": categories[0]-> {\n    name,\n    "slug": slug.current\n  }\n}': SEARCH_ARTICLES_QUERY_RESULT;
    ' \n  *[_type == "author" && slug.current == $slug && language == $locale && !(_id in path(\'drafts.**\'))][0]{\n    _id,\n    name, \n    bio,\n    "image": image.asset->url,\n    "alt": image.alt,\n    socials[]{platform, url},\n    // Fetch translations for the Language Switcher\n    "translations": *[\n      _type == ^._type && \n      _id match string::split(^._id, "__i18n_")[0] + "*" && \n      _id != ^._id && \n      !(_id in path(\'drafts.**\'))\n    ] {\n      "language": language,\n      "slug": slug.current\n    }\n  }\n': GET_AUTHOR_BY_SLUG_RESULT;
    "\n  count(*[\n    _type == \"article\" &&\n    author._ref == $authorId &&\n    language == $locale && \n    !(_id in path('drafts.**'))\n  ])\n": ARTICLES_IN_AUTHOR_COUNT_RESULT;
    '\n  *[_type == "article" && _id == $articleId && !(_id in path(\'drafts.**\'))][0].author-> {\n    name,\n    "slug": slug.current,\n    bio\n  }\n': AUTHOR_BY_ARTICLE_ID_RESULT;
    '\n  *[_type == "category" && language == $locale && !(_id in path(\'drafts.**\'))] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current\n  }\n': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug && language == $locale && !(_id in path(\'drafts.**\'))][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    \n    // Fetch translations for the Language Switcher\n    "translations": *[\n      _type == ^._type && \n      _id match string::split(^._id, "__i18n_")[0] + "*" && \n      _id != ^._id && \n      !(_id in path(\'drafts.**\'))\n    ] {\n      "language": language,\n      "slug": slug.current\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    "\n  count(*[\n    _type == \"article\" && \n    $slug in categories[]->slug.current && \n    language == $locale && \n    !(_id in path('drafts.**'))\n  ])\n": ARTICLES_IN_CATEGORY_COUNT_RESULT;
    "\n  *[_type == \"comment\" && approved == true && article._ref == $_id && !(_id in path('drafts.**'))] | order(_createdAt desc) [$start...$end] { \n    _id, \n    name,\n    message,\n    _createdAt\n  }\n": GET_COMMENTS_BY_ARTICLE_RESULT;
    "\n  count(*[\n    _type == \"comment\" &&\n    approved == true &&\n    article._ref == $_id && // Fixed typo here (was article_ref)\n    !(_id in path('drafts.**'))\n  ])\n": TOTAL_COMMENTS_COUNT_RESULT;
  }
}
